version: '3.8'
services:
  neo4j:
    image: neo4j:5.22
    container_name: argan-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4JLABS_PLUGINS=["apoc","graph-data-science"]
    volumes:
      - ./data:/data
      - ./queries:/queries